config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#homepage'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :products
  resources :carts
  resources :cart_products
  resources :orders
  resources :restaurants

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  # Added by administrate gem
  namespace :admin do
    resources :users
    resources :orders
    resources :order_products
    resources :carts
    # resources :cart_products
    resources :categories
    resources :products
    resources :ingredients
    resources :units
    resources :product_ingredients
    resources :restaurants
    resources :comments

    root to: "carts#index"
  end
end

app/models/user.rb
class User < ApplicationRecord
  geocoded_by :full_address
  after_validation :geocode, if: :full_address_changed?
  before_save :set_default_restaurant

  after_initialize :set_default_role, :if => :new_record?
  after_save :set_user_cart
  after_create :send_welcome_email 

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  enum role: [:client, :manager, :admin]

  belongs_to :restaurant, optional: true
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :working_restaurants, foreign_key: 'employee', class_name: 'RestaurantEmployee', dependent: :destroy
  has_many :restaurants, through: :working_restaurants

  validates :firstname, :lastname, :address, :zipcode, :city, :email, :phone, presence: true, 
    allow_blank: true,
  on: :create
  validates :firstname, :lastname, presence: true, 
    length: { minimum: 2, maximum: 20, message: "doit être compris entre 2 et 20 caractères" }, 
    format: { with: /\A[a-zA-Z\-\'\s\é\è\ê\ç]+\z/ , message: "ne doit contenir que des lettres" },
  on: :update
  validates :address, presence: true, 
    length: { minimum: 5, maximum: 100 }, 
  on: :update
  validates :zipcode, presence: true, 
    numericality: { only_integer: true, greater_than: 01000, less_or_equal_to: 99138 }, 
    length: { is: 5 }, 
  on: :update
  validates :city, presence: true, 
    length: { minimum: 2, maximum: 30 }, 
    format: { with: /\A[a-zA-Z\-\'\s\é\è\ê\ç]+\z/ }, 
  on: :update
  validates :phone, presence: true, 
    length: { is: 10, message: "doit être composé de 10 chiffres" }, 
    format: { with: /\A[0]{1}[1-7]{1}[0-9]{8}\z/, 
      message: "doit être composé de 10 chiffres et commencer par 0" }, 
  on: :update

  def status
    if self.orders.any?
      stage = self.orders.pluck(:total).sum
      case stage
        when 0...100
          status = 'Gouteur'
        when 100...250
          status = 'Petit gourmand'
        when 250...500
          status = 'Gourmand'
        else
          status = 'Gourmand d\'élite'
        end
    end
  end

  def fullname
    "#{firstname.capitalize} #{lastname.upcase}"
  end

  def full_address
    # [address, zipcode, city].compact.join(', ')
    [zipcode, city].compact.join(', ')
  end

  def full_address_changed?
    # self.address_changed? || self.zipcode_changed? || self.city_changed?
    self.zipcode_changed? || self.city_changed?
  end

  def profile_complete?
    !(self.firstname && self.lastname && self.address && self.zipcode && self.city && self.phone).blank?
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_now
  end
  
  private
  def set_default_role
    self.role ||= :client
  end

  def set_user_cart
    self.cart ||= Cart.create(user: self)
  end

  def set_default_restaurant
    # default_restaurant = Restaurant.near(self.to_coordinates).first
    # self.restaurant = default_restaurant
    self.restaurant = Restaurant.near(self.to_coordinates, 15).first
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! && :restrict_to_user

  def show
    @user = User.find(params[:id])
    @orders = @user.orders.order(created_at: :desc).limit(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    @restaurant = Restaurant.find(params[:user][:restaurant_id])
    if @user.update_columns(restaurant_id: user_params[:restaurant_id])
      respond_to do |format|
        format.html { redirect_to @user, notice: 'Votre profil a été mis à jour.' }
        format.js { @restaurant }
      end
    else
      respond_to do |format|
        format.html { render :edit, notice: 'Votre profil n\'a pas pu être mis à jour.' }
      end
    end
  end

  private
  def restrict_to_user
    if current_user.id != params[:id].to_i
      flash[:alert] = "L'accès à cette page ne vous est pas autorisé"
      redirect_to root_path
    end
  end

  def user_params
    # params.require(:user).permit(:firstname, :lastname, :address, :city, :phone, :zipcode, :restaurant_id)
    params.require(:user).permit(:restaurant_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<section class="row justify-content-center py-5">
  <h1 class="mb-3">Mon espace client</h1>
  <div class="col-md-10 border py-3 mt-3 text-center">
    <% unless @orders.any? %>
      <p>Passez votre 1ère commande pour débloquer votre nouveau status et gagner des réductions!</p>
    <% else %>
      <p class="fs-4">Féliciations <%= current_user.fullname %> </p>
      <p>vous avez atteint le rang de <%= current_user.status %>.</p> 
    <% end %>
      <%= link_to 'Commander', :products, class:'btn btn-lg btn-custom' %>
  </div>
</section>

<section class="row my-5">
  <div class="col-12 col-md-6">
  <h2>Profil</h2>
  <hr>
    <p>
      <strong>M./Mme :</strong> <%= @user.fullname %>
    </p>
    <!-- <p>
      <strong>Prénom :</strong> <%#= @user.firstname %>
    </p> %>
    <p> -->
      <strong>Adresse :</strong> <%= @user.address %>
    </p>
    <p>
      <strong>Code postal :</strong> <%= @user.zipcode %>
    </p>
    <p>
      <strong>Ville :</strong> <%= @user.city %>
    </p>
    <p>
      <strong>Téléphone :</strong> <%= @user.phone %>
    </p>
    <p>
      <strong>Email :</strong> <%= @user.email %>
    </p>
    <%= link_to 'Editer', edit_user_registration_path(@user), class: 'btn btn-lg btn-custom' %>
  </div>
  <div id="restaurant_info" class="col-12 col-md-6">
      <h2>Mon restaurant préféré</h2>
      <hr>
    <p id="selected_restaurant" class="">
    <% if @user.profile_complete? %>
      <% if @user.restaurant.nil? && Restaurant.near(@user.to_coordinates, 50) != [] %>
        <div class="alert alert-info" role="alert">
          <p>Aucun restaurant trouvé à moins de 20km de votre domicile. Merci de le sélectionner manuellement.</p> 
          <%= form_for @user do |f| %>
            <%= f.collection_select :restaurant_id, Restaurant.near(@user.to_coordinates, 50, order: 'distance').limit(3), :id, :city, class: 'form-control' %>
            <%= f.submit 'Sélectionner', class: 'btn btn-custom' %>
          <%end%>
        </div>
      <% elsif Restaurant.near(@user.to_coordinates, 50).empty? %>
        <div class="alert alert-warning" role="alert">
          <p>Nous sommes désolé mais aucun restaurant ne ce trouve encore dans un rayon de 50Km de <%= @user.city %></p>
        </div>
      <% else %>
      <p> <strong>Nom : </strong><%= @user.restaurant.name %></p>
      <p> <strong>Adresse :</strong> <%= @user.restaurant.address %></p>
      <p> <strong>Code postal :</strong> <%= @user.restaurant.zipcode %></p>
      <p> <strong>Ville :</strong> <%= @user.restaurant.city %></p>
      <p> <strong>Téléphone :</strong> <%= @user.restaurant.phone %></p>
      <p> <strong>Email :</strong> <%= @user.restaurant.email %></p>
      <%# Button to display bootstrap modal %>
      <%= link_to 'Changer', '#', class: 'btn btn-lg btn-custom', data: {'bs-toggle': 'modal', 'bs-target': '#change_restaurant'} %>
      
      <%# modal to change restaurant %>
      <div class="modal fade" id="change_restaurant" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="myModalLabel">Sélection manuelle</h4>
            </div>
            <div class="modal-body">
              <%= form_for @user do |f| %>
                <%= f.collection_select :restaurant_id, Restaurant.all, :id, :city, class: 'form-control' %>
            </div>
            <div class="modal-footer">
              <%= f.submit 'Enregistrer', class: 'btn btn-custom' %>
            </div>
              <%end%>
          </div>
        </div>
      
      <% end %>
      <%else %>
      <div class="alert alert-warning" role="alert">
        <p>Merci de compléter votre profil</p>
      </div>
      <%end %>
    </p>
  </div>
</section>


<section class="row my-5">
  <h2>Historique des commandes</h2>
  <hr>
  <div class="col-12 col-md-6">
    <table class="table table-striped table-hover">
      <% if @orders.any? %>
        <thead>
          <tr>
            <th>Date</th>
            <th>Référence</th>
            <th>Montant</th>
            <th>Statut</th>
            <th>Voir</th>
            <th>Facture</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.created_at.strftime('%d/%m/%Y') %></td>
              <td><%= order.reference %></td>
              <td><%= sprintf('%.2f', order.total) %> €</td>
              <td>Livrée</td>
              <td>
                <%= link_to order_path(order), class:'btn btn-sm btn-custom', remote: true do %>
                  <i class="bi bi-plus"></i>
                <% end %>
              </td>
              <td>
                <% unless order.invoice_url.blank? %>
                  <%= link_to "#{order.invoice_url}", target: '_blank', class:'btn btn-sm btn-custom' do %>
                    <i class="bi bi-download"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      <% else %>
        <tr>
          <td colspan="3">Aucune commande</td>
        </tr>
      <% end %>
    </table>
  </div>
  
  <div class="col-12 col-md-6">
    <div id="order_details">
      <%# AJAX RESPONSE ONLY %>
    </div>
  </div>
</section>

<%= link_to 'Retour', :products, class: 'btn btn-custom' %>

app/views/users/update.js.erb
document.querySelectorAll('#edit_user_<%=current_user.id%>').forEach(function(element) {
  if (element.querySelector('#user_restaurant_id').value == <%= @restaurant.id %>) {
    element.lastElementChild.innerHTML = '<i class="bi-heart-fill"></i>';
  } else {
    element.lastElementChild.innerHTML = '<i class="bi-heart"></i>';
  }
});