config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#homepage'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :products
  resources :carts
  resources :cart_products
  resources :orders
  resources :restaurants

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  # Added by administrate gem
  namespace :admin do
    resources :users
    resources :orders
    resources :order_products
    resources :carts
    # resources :cart_products
    resources :categories
    resources :products
    resources :ingredients
    resources :units
    resources :product_ingredients
    resources :restaurants
    resources :comments

    root to: "carts#index"
  end
end

app/views/shared/_flash_messages.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-md-6 col-lg-4">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', alt: 'Logo pizzaYolo', height: '50px' %>
      <span class="navbar-brand">PizzaYolo</span>
    <%end%>
    <%= button_tag class: 'navbar-toggler', type: 'button', 
      data: {'bs-toggle': 'collapse', 'bs-target': '#navbarNavAltMarkup'}, 
      aria: { controls: 'navbarNavAltMarkup', expanded: 'false', label: 'Toggle navigation'} do %>
      <span class="navbar-toggler-icon"></span>
    <%end%>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Offres', root_path(anchor: 'offres'), class: 'nav-link' %>
        <%= link_to 'Restaurants', restaurants_path, class: 'nav-link' %>
        <%= link_to 'Carte', products_path, class: 'nav-link' %>
        <%= link_to 'Contact', root_path, class: 'nav-link' %>
      </div>
    </div>
    <div class='navbar-nav'>
      <% if user_signed_in? %>
        <%= link_to cart_path(current_user.cart), class: 'btn btn-custom position-relative' do %>
          <span>Panier</span>
          <span id="cart_product_sum" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-dark">
            <%= current_user.cart.total_products %>
          </span>
        <%end%>
        <%= link_to 'Mon compte', user_path(current_user), class: 'nav-link' %>
        <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <%else%>
        <%= link_to 'Connexion', new_user_session_path, class: 'btn btn-custom' %>
      <%end%>
    </div>
  </div>
</nav>