config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#homepage'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :products
  resources :carts
  resources :cart_products
  resources :orders
  resources :restaurants

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  # Added by administrate gem
  namespace :admin do
    resources :users
    resources :orders
    resources :order_products
    resources :carts
    # resources :cart_products
    resources :categories
    resources :products
    resources :ingredients
    resources :units
    resources :product_ingredients
    resources :restaurants
    resources :comments

    root to: "carts#index"
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products

  
  def total_price
    total = 0
    self.cart_products.each do |cart_product|
      total += cart_product.product.price * cart_product.quantity
    end
    total
  end

  def total_products
    total = 0
    self.cart_products.each do |cart_product|
      total += cart_product.quantity
    end
    total
  end

end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  def new
    @cart = Cart.new(user_id: params[:id])
  end

  def create
    if current_user.cart == nil
      @cart = Cart.new(cart_params)
      @cart.user_id = current_user.id
      @cart.save
    else
      @cart = current_user.cart
    end
  end

  def show
    if current_user.cart != nil
      @cart = current_user.cart
      # @products = @cart.cart_products.order(:created_at)
      # @products = @cart.cart_products.order(:created_at).map(&:product)
      #@cart_products = @cart.cart_products.includes(:product).group_by { |cp| cp.product.category } 
      @cart_products = @cart.cart_products.includes(:product).group_by { |cp| cp.product.category }.sort_by { |category, products| category.id }
      @cart_products.each do |category, products|
        products.sort_by! { |cp| cp.product.name }
      end
    else
      @cart = Cart.new(user_id: current_user.id)
      @cart.save!
    end
  end

  def destroy
    @cart = current_user.cart # Added after bug 03072022
    @cart.cart_products.destroy_all
    respond_to do |format|
      format.html { redirect_to @cart, notice: 'Cart was successfully destroyed.' }
      format.js {}
    end
  end

  private
  def set_cart
    @cart = Cart.find_by(user_id: params[:id])
  end

  def cart_params
    params.require(:cart).permit(:user_id)
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<div class="div-custom">
<h1>Carts#show</h1>
<br>
</div>

<% unless @cart_products.empty? %>
  <% @cart_products.each do |categorie, cart_product| %>
      <h2 class="mt-5">Vos<%= pluralize("",categorie.name.downcase) %></h2>
      <hr>
    <% cart_product.each do |cp| %>
      <div id="cp_<%=cp.id%>" class="py-3">
        
        <%= cp.product.name %>
        <br>
        Quantité: 
        <%= link_to "-", cart_product_path(cp, decrement: "true"), method: 'put', class: 'btn btn-sm btn-custom', remote: true %>
        <span class="mx-3 fw-bold"><%= cp.quantity %></span>
        <%= link_to "+", cart_product_path(cp, increment: "true"), method: 'put', class: 'btn btn-sm btn-custom', remote: true %>
        <br>
        Sous-total: <%= sprintf('%.2f', cp.quantity * cp.product.price) %> &euro;
      
      </div>
    <%end%>
  <% end %>
<hr>
  <p class='fs-3'>
    <span id="total_cart">TOTAL : <%= sprintf('%.2f', @cart.total_price) %> &euro; <br></span>
    <% unless current_user.restaurant.nil? %>
      <%= link_to "Payer", checkout_create_path, method: :post, remote: true, class: 'btn btn-custom' %>
      <% else %>
      <%= link_to "Choisir mon restaurant", user_path(current_user), class: 'btn btn-custom' %>
    <% end %>
  </p> 
<hr>
  <%= link_to "Retour", products_path, class: 'btn btn-custom' %>
  <%= link_to "Vider le panier", @cart, method: :delete, class: 'btn btn-custom' %>
<% else %>
  <p>Votre panier est vide</p>
  <%= link_to "La carte", products_path, class: 'btn btn-custom' %>
<% end %>