config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#homepage'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :products
  resources :carts
  resources :cart_products
  resources :orders
  resources :restaurants

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  # Added by administrate gem
  namespace :admin do
    resources :users
    resources :orders
    resources :order_products
    resources :carts
    # resources :cart_products
    resources :categories
    resources :products
    resources :ingredients
    resources :units
    resources :product_ingredients
    resources :restaurants
    resources :comments

    root to: "carts#index"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :restaurant_products
  has_many :restaurants, through: :restaurant_products
  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :product_ingredients
  has_many :ingredients, through: :product_ingredients

  validates :name, presence: true,
    length: { minimum: 3, maximum: 50 },
    format: { with: /\A[a-zA-Z\s'-]+\z/ },
    uniqueness: { case_sensitive: false }
  validates :description, presence: true,
    length: { minimum: 3, maximum: 150 }
  validates :price, presence: true,
    length: { minimum: 1, maximum: 5 },
    format: { with: /\A\d+(?:\.\d{0,2})?\z/ }
  validates :image_url, presence: true,
    length: { maximum: 255 },
    format: { with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix }

  end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category_id].present?
      @products = Product.where(category_id: params[:category_id]).includes(:category).group_by { |p| p.category }.map { |k, v| [k, v.sort_by(&:name)] }
    else
      @products = Product.includes(:category).group_by { |p| p.category }.sort_by { |category, products| category.id }
      @products.each do |category, products|
        products.sort_by! { |p| p.name }
      end
    end
    respond_to do |format|
      format.html { render :index }
      format.js {}
    end
  end

  def show
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_products.html.erb
  <% all_products.each do |categorie, products| %>
    <div class="col-12 col-md-10 col-lg-8 mb-5">
      <h2 class="text-center mb-2">Carte des <%= pluralize('',categorie.name.downcase) %></h2>
      <h4 class="text-center fw-light"><%= categorie.description %></h4>
    </div>

    <div id="products" class="row justify-content-start mt-5">
      <% products.each do |product| %>
      <div class="col-md-4 col-lg-4 mb-5">
        <div class="card border-0">
          <div class="d-flex justify-content-center align-items-center h-100">
            <%= image_tag "https://via.placeholder.com/150", class:'rounded-circle' %>
          </div>
          <div class="card-body">
            <div class="d-flex-column text-center">
              <h2><%= product.name %></h2>
              <p class="fs-3"><%= sprintf('%.2f', product.price) %><span class="fs-2"> &euro;</span></p>
            </div>
            <p class="card-text"><%= product.description %></p>
            <div class="d-flex justify-content-evenly">
              <%= link_to 'Découvrir', product, class:'btn btn-custom p-3' %>
              <%= link_to 'Ajouter au panier', cart_products_path(id:product), method: :post, class:'btn btn-custom p-3', remote: true %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>

app/views/products/index.html.erb
<section class="row py-2 my-5">
  <div class="d-flex-column align-items-center justify-content-center text-center">
    <h1>Carte</h1>
    <p>Notre savoir-faire, pour vous satisfaire</p>
  </div>
  <nav class="nav nav-pills nav-fill justify-content-center"></a>
    <%= link_to 'Pizza', products_path(category_id: 1), class:'btn btn-custom mx-md-3', remote: true %>
    <%= link_to 'Desserts', products_path(category_id: 3), class:'btn btn-custom mx-md-3', remote: true %>
    <%= link_to 'Boissons', products_path(category_id: 2), class:'btn btn-custom mx-md-3', remote: true %>
  </nav>
</section>

<%# products %>
<section  id="products" class="row justify-content-center py-2 mt-5">
  <% @products.each do |categorie, products| %>
    <div class="col-12 col-md-10 col-lg-8 mb-5">
      <h2 class="text-center mb-2">Carte des <%= pluralize('',categorie.name.downcase) %></h2>
      <h4 class="text-center fw-light"><%= categorie.description %></h4>
    </div>

    <div class="row justify-content-start mt-5">
      <% products.each do |product| %>
      <div class="col-md-4 col-lg-4 mb-5">
        <div class="card border-0">
          <div class="d-flex justify-content-center align-items-center h-100">
            <%= image_tag "https://via.placeholder.com/150", class:'rounded-circle' %>
          </div>
          <div class="card-body">
            <div class="d-flex-column text-center">
              <h2><%= product.name %></h2>
              <p class="fs-3"><%= sprintf('%.2f', product.price) %><span class="fs-2"> &euro;</span></p>
            </div>
            <p class="card-text"><%= product.description %></p>
            <div class="d-flex justify-content-evenly">
              <%= link_to 'Découvrir', product, class:'btn btn-custom p-3' %>
              <% if user_signed_in? %>
                <%= link_to 'Ajouter au panier', cart_products_path(id:product), method: :post, class:'btn btn-custom p-3', remote: true %>
              <% else %>
                <%= link_to 'Se connecter', new_user_session_path, class:'btn btn-custom p-3' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
</section>

app/views/products/index.js.erb
document.getElementById('products').innerHTML = "";
document.getElementById('products').insertAdjacentHTML('beforeend', "<%= j render 'products/products', all_products: @products %>");

app/views/products/show.html.erb
<section class="row my-5 section-centered">
  <div class="col-12 col-md-6">
    <div class="wrapper d-flex align-items-center justify-content-center h-100">
      <%= image_tag("https://via.placeholder.com/450?text=Pizza-Yolo", class:'img-fluid') %>  
    </div>
  </div>
  <div class="col-12 col-md-6">
    <div class="d-flex flex-column justify-content-center h-100">
      <div class="d-flex justify-content-between">
        <h2><%= @product.name %></h2>
        <p class="fs-3"><%= sprintf('%.2f', @product.price) %><span class="fs-2"> &euro;</span></p>
      </div>
      <div>
        <span class="badge rounded-pill bg-dark"><%= @product.category.name %></span>
      </div>
      <div class="d-flex flex-column align-items-center justify-content-center my-5">
        <p><%= @product.description %></p>
      </div>
      <div class="d-flex justify-content-between">
        <% if user_signed_in? %>
          <%= link_to 'Ajouter au panier', cart_products_path(id:@product), method: :post, class:'btn btn-custom p-3' %>
        <% else %>
          <%= link_to 'Se connecter', new_user_session_path, class:'btn btn-custom p-3' %>
        <% end %>
        <%= link_to 'La carte', :products, class:'btn btn-custom p-3' %>
      </div>
    </div>
  </div>
</section>